version: 2

models:
  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null

  - name: dim_customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: fct_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null


  - name: mart_orders_core
    tests:
      - unique:
          column_name: order_id
      - not_null:
          column_name: order_id
    columns:
      - name: total_order_value
        tests:
          - not_null

  - name: mart_product_performance
    tests:
      - not_null:
          column_name: product_perf_key
    columns:
      - name: revenue
        tests:
          - not_null
